/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Dec  1 16:06:02 2025


#ifndef ISAACSIMCONTROLBOARDNWCROS2_PARAMSPARSER_H
#define ISAACSIMCONTROLBOARDNWCROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class IsaacSimControlBoardNWCROS2.
*
* These are the used parameters:
* | Group name | Parameter name              | Type   | Units   | Default Value               | Required | Description                                                           | Notes                                                           |
* |:----------:|:---------------------------:|:------:|:-------:|:---------------------------:|:--------:|:---------------------------------------------------------------------:|:---------------------------------------------------------------:|
* | -          | streaming_node_name         | string | -       | ControlBoardBridgeStreaming | 0        | Set the name for the ROS node streaming and receiving the state       | Must not start with a leading '/'                               |
* | -          | service_node_name           | string | -       | ControlBoardBridgeService   | 0        | Set the name for the ROS node connecting to the services              | Must not start with a leading '/'                               |
* | -          | joint_state_topic_name      | string | -       | -                           | 1        | Specify the name of the joint state topic to connect                  | The message type is JointState. Should start with a leading '/' |
* | -          | motor_state_topic_name      | string | -       | -                           | 1        | Specify the name of the motor state topic to connect                  | The message type is JointState. Should start with a leading '/' |
* | -          | joint_references_topic_name | string | -       | -                           | 1        | Specify the name of the topic to open to publish the joint references | The message type is JointState. Should start with a leading '/' |
* | -          | get_parameters_service_name | string | -       | -                           | 1        | Specify the name of the service for getting parameters from IsaacSim  | Should start with a leading '/'                                 |
* | -          | set_parameters_service_name | string | -       | -                           | 1        | Specify the name of the service for setting parameters to IsaacSim    | Should start with a leading '/'                                 |
* | -          | service_request_timeout     | double | seconds | 0.5                         | 0        | Specify the timeout value for getting and setting parameters          | Should start with a leading '/'                                 |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device IsaacSimControlBoardNWCROS2 --streaming_node_name ControlBoardBridgeStreaming --service_node_name ControlBoardBridgeService --joint_state_topic_name <mandatory_value> --motor_state_topic_name <mandatory_value> --joint_references_topic_name <mandatory_value> --get_parameters_service_name <mandatory_value> --set_parameters_service_name <mandatory_value> --service_request_timeout 0.5
* \endcode
*
* \code{.unparsed}
* yarpdev --device IsaacSimControlBoardNWCROS2 --joint_state_topic_name <mandatory_value> --motor_state_topic_name <mandatory_value> --joint_references_topic_name <mandatory_value> --get_parameters_service_name <mandatory_value> --set_parameters_service_name <mandatory_value>
* \endcode
*
*/

class IsaacSimControlBoardNWCROS2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    IsaacSimControlBoardNWCROS2_ParamsParser();
    ~IsaacSimControlBoardNWCROS2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"IsaacSimControlBoardNWCROS2"};
    const std::string m_device_name = {"IsaacSimControlBoardNWCROS2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_streaming_node_name_defaultValue = {"ControlBoardBridgeStreaming"};
    const std::string m_service_node_name_defaultValue = {"ControlBoardBridgeService"};
    const std::string m_joint_state_topic_name_defaultValue = {""};
    const std::string m_motor_state_topic_name_defaultValue = {""};
    const std::string m_joint_references_topic_name_defaultValue = {""};
    const std::string m_get_parameters_service_name_defaultValue = {""};
    const std::string m_set_parameters_service_name_defaultValue = {""};
    const std::string m_service_request_timeout_defaultValue = {"0.5"};

    std::string m_streaming_node_name = {"ControlBoardBridgeStreaming"};
    std::string m_service_node_name = {"ControlBoardBridgeService"};
    std::string m_joint_state_topic_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_motor_state_topic_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_joint_references_topic_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_get_parameters_service_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_set_parameters_service_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    double m_service_request_timeout = {0.5};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
